name: Node CI

on: [push]

env:
    TRIG_NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    CODE_COV_TOKEN: ${{ secrets.CODE_COV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm config set //registry.npmjs.org/:_authToken=$TRIG_NPM_TOKEN
        npm ci
        npm run lint
        npm test
      env:
        CI: true
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # Repository upload token - get it from codecov.io
        token: $CODE_COV_TOKEN
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
