export const mockCards = {
  data: [
    {
      id: 37,
      token: '52c26ef1996edae58640b956b5974124e00cd245f77637a8',
      userId: 7,
      title: 'Navigating the Product Maze',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/1200/674',
      imageWidth: 1200,
      imageHeight: 674,
      createdAt: '2020-11-28T07:15:46+00:00',
      url:
        'https://medium.com/lets-make-things/navigating-the-product-maze-f7dce97eeb34',
      totalFavorites: 0,
      description: 'Or, The Elementary Forces of Product Design.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T07:15:53+00:00',
    },
    {
      id: 35,
      token: 'ed9f1d6a14ee0c78100c4fc1e97b0c5e25d4698f89a29aec',
      userId: 7,
      title: "Designing Your Product's Continuous Feedback Loop",
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/800/450',
      imageWidth: 800,
      imageHeight: 450,
      createdAt: '2020-11-28T07:15:14+00:00',
      url:
        'https://medium.com/@sachinrekhi/designing-your-products-continuous-feedback-loop-4a7bb31141fe',
      totalFavorites: 0,
      description:
        'While every product team I\u2019ve worked with leverages customer feedback to inform product decisions in some way, most fall short of designing\u2026',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T07:15:21+00:00',
    },
    {
      id: 33,
      token: '70ed33afb587ceb836cdc474a0eb0eccf8eda20f13814298',
      userId: 7,
      title: 'Product managers for the digital world',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/1536/1536',
      imageWidth: 1536,
      imageHeight: 1536,
      createdAt: '2020-11-28T07:15:02+00:00',
      url:
        'https://www.mckinsey.com/industries/high-tech/our-insights/product-managers-for-the-digital-world',
      totalFavorites: 0,
      description:
        'The role of the product manager is expanding due to the growing importance of data in decision making, an increased customer and design focus, and the evolution of software-development methodologies.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T07:15:09+00:00',
    },
    {
      id: 32,
      token: '45480b367c877e271d0da927052ac3af4c73e6a7fe02361a',
      userId: 7,
      title:
        'The Power of the Elastic Product Team & Airbnb\u2019s First PM on How to Build Your Own',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/640/426',
      imageWidth: 640,
      imageHeight: 426,
      createdAt: '2020-11-28T07:14:54+00:00',
      url:
        'http://firstround.com/review/the-power-of-the-elastic-product-team-airbnbs-first-pm-on-how-to-build-your-own/',
      totalFavorites: 0,
      description:
        "Over the last 5 years, Jonathan Golden has watched Airbnb explode in size and productivity. Here's what that journey looked like on the product team that powered it.",
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T07:15:01+00:00',
    },
    {
      id: 31,
      token: '7b971f9dfb60340838d476abe7cca6888e6d2fde9c3cd19b',
      userId: 7,
      title: 'Top 5 Ways to Deal with Difficult People',
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T07:14:33+00:00',
      url:
        'https://www.100productmanagers.com/articles/top-5-ways-to-deal-with-difficult-people',
      totalFavorites: 0,
      description:
        'Top 5 ways to deal with difficult people written by a product manager, for product managers.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T07:14:45+00:00',
    },
    {
      id: 30,
      token: 'b7facdb36f57d50a7d324b3f55966e6b1c66aa09919ffb90',
      userId: 7,
      title: 'All the Responsibility with Limited Authority',
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T07:14:26+00:00',
      url:
        'https://www.100productmanagers.com/articles/all-the-responsibility-with-limited-authority',
      totalFavorites: 0,
      description:
        'The key differences between industrial and technical product management.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T07:14:31+00:00',
    },
    {
      id: 29,
      token: '8feb26641e81923c98e7594bef7ffb8c2f15b51ff2255ff8',
      userId: 7,
      title: "If your product is Great, it doesn't need to be Good.",
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T00:19:19+00:00',
      url:
        'http://paulbuchheit.blogspot.com/2010/02/if-your-product-is-great-it-doesnt-need.html',
      totalFavorites: 0,
      description:
        'By now, everyone is tired of hearing about the iPad, but the negative responses are so perfectly misguided that it would be wrong to waste t...',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:19:24+00:00',
    },
    {
      id: 24,
      token: 'da54fb56115a00e7ecb0ca1544d9b4c2b696244624b4fc0d',
      userId: 7,
      title: 'Writing,  Briefly',
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T00:18:54+00:00',
      url: 'http://www.paulgraham.com/writing44.html',
      totalFavorites: 0,
      description:
        "I think it's far more important to write well than most people\nrealize.  Writing doesn't just communicate ideas; it generates them.\nIf you're bad at writing and don't like to do it, you'll miss out\non most of the ideas writing would have generated.",
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:19:05+00:00',
    },
    {
      id: 23,
      token: '70bcfe42ec691ab9e7467e64b888666ac42595d09acdb1f7',
      userId: 7,
      title: '"Writing is Thinking" an annotated twitter thread',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/1200/632',
      imageWidth: 1200,
      imageHeight: 632,
      createdAt: '2020-11-28T00:18:49+00:00',
      url:
        'https://medium.learningbyshipping.com/writing-is-thinking-an-annotated-twitter-thread-2a75fe07fade',
      totalFavorites: 0,
      description:
        '"Writing is thinking" is my favorite expression for how to work in a company. This annotated thread explores the value of writing.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:19:03+00:00',
    },
    {
      id: 21,
      token: 'd461b0359b0e85797d61976d88edced68599cb62a66df45e',
      userId: 7,
      title: 'The "Oh, Shit!" Moment When Growth Stops - Andreessen Horowitz',
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T00:18:34+00:00',
      url: 'http://a16z.com/2015/09/30/what-to-do-if-growth-stops/',
      totalFavorites: 0,
      description:
        'Investors tend to value growth over everything else because a business can\u2019t get big enough to break out if it isn\u2019t growing. Of course, there are a number of key performance indicators for managing a business well and toward profitability -- which we\u2019ve written about here -- but there are still stomach-churning moments where growth trajectory was interrupted. \n\nSometimes it happens gradually, but in a surprising number of cases it happens suddenly: The business is growing one day, then it\u2019s not growing the next. I\u2019ve taken to calling these growth hiccups \u201cOh, shit!\u201d moments for CEOs. So what do you do when the growth rocket judders? MORE',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:18:41+00:00',
    },
    {
      id: 20,
      token: '5adfc1141d93c723f97b426aff3de027e2ecf4c99a54b380',
      userId: 7,
      title: 'Design for Continuous Experimentation',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/768/689',
      imageWidth: 768,
      imageHeight: 689,
      createdAt: '2020-11-28T00:18:29+00:00',
      url:
        'http://www.slideshare.net/danmckinley/design-for-continuous-experimentation',
      totalFavorites: 0,
      description:
        'Presented at Warmgun design conference, 2012. Video: http://mcfunley.com/design-for-continuous-experimentation',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:18:37+00:00',
    },
    {
      id: 19,
      token: '1d71a85309753416e5e5cacab39cb488e9197afeac8414f4',
      userId: 7,
      title: 'Diligence at Social Capital Part 1: Accounting for User Growth',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/434/292',
      imageWidth: 434,
      imageHeight: 292,
      createdAt: '2020-11-28T00:18:21+00:00',
      url:
        'https://medium.com/swlh/diligence-at-social-capital-part-1-accounting-for-user-growth-4a8a449fddfc',
      totalFavorites: 0,
      description:
        '[Note from the author: See an update to the thinking presented in these articles here. I no longer work at Social Capital, if you want to\u2026',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:18:28+00:00',
    },
    {
      id: 18,
      token: 'cb4299bcc7e6c6bce9fe0c42173d94d6ffa7888c6ad9fa9a',
      userId: 7,
      title:
        "IAC's HowAboutWe co-founder: How to Avoid Delusional Thinking in Start-up Growth Strategy (Guest Post)",
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/310/206',
      imageWidth: 310,
      imageHeight: 206,
      createdAt: '2020-11-28T00:18:15+00:00',
      url:
        'http://andrewchen.co/iacs-howaboutwe-co-founder-how-to-avoid-delusional-thinking-in-start-up-growth-strategy-guest-post/',
      totalFavorites: 0,
      description:
        '[Andrew: Trying to build and launch dating apps is a favorite pastime of 20-something tech entrepreneurs. However, dating products are notoriously hard to grow because it requires people to be \u201cin-market\u201d and also they don\u2019t necessarily want their friends to know they\u2019re online dating. Today, we have a great piece from a veteran of the \u2026',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:18:20+00:00',
    },
    {
      id: 17,
      token: 'a11bc492cb073ccb0922223040bd86cf1018da319d3c4586',
      userId: 7,
      title: 'The Agony and Ecstasy of Building with Data',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/700/438',
      imageWidth: 700,
      imageHeight: 438,
      createdAt: '2020-11-28T00:17:49+00:00',
      url:
        'https://medium.com/the-year-of-the-looking-glass/the-agony-and-ecstasy-of-building-with-data-56215764d67c',
      totalFavorites: 0,
      description:
        'They\u2019re like the the It couple of many a young software company these days. You can\u2019t seem to turn a corner or make a sandwich without encountering their know-it-all allure or the gleaming exactness\u2026',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:17:54+00:00',
    },
    {
      id: 16,
      token: '42e2af0a0ed96b12e353922913ca1d9b59f949ef15e23c6e',
      userId: 7,
      title: 'Bad Managers Talk, Good Managers Write',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/600/400',
      imageWidth: 600,
      imageHeight: 400,
      createdAt: '2020-11-28T00:17:29+00:00',
      url: 'http://blog.idonethis.com/managers-write/',
      totalFavorites: 0,
      description:
        'One of the most vital skills you can have as a manager is the ability to write. When managers write, they raise accountability, coherence, and commitment.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:17:47+00:00',
    },
    {
      id: 15,
      token: 'a91e8a6fb89caced33554558027874e9c76a32e22e6c048e',
      userId: 7,
      title: "Top Hacks from a PM Behind Two of Tech's Hottest Products",
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T00:17:19+00:00',
      url:
        'https://firstround.com/review/Top-Hacks-from-a-PM-Behind-Two-of-Techs-Hottest-Products/',
      totalFavorites: 0,
      description:
        "Todd Jackson has experience managing products at Google, Facebook and his own startup. Here's what he learned.",
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:17:24+00:00',
    },
    {
      id: 14,
      token: '24d48e35481f5488becd5871ef7d82e862b8b1472a109737',
      userId: 7,
      title: 'Getting Started \u2013 React',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/1200/630',
      imageWidth: 1200,
      imageHeight: 630,
      createdAt: '2020-11-28T00:16:45+00:00',
      url: 'https://reactjs.org/docs/getting-started.html',
      totalFavorites: 1,
      description: 'A JavaScript library for building user interfaces',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: { card_id: 14 },
      isFavorited: true,
      lastAttemptedSync: '2020-11-28T00:16:48+00:00',
    },
    {
      id: 13,
      token: 'f643db9f623821d66e226466313616630bf4f539290bf67c',
      userId: 7,
      title: 'Loop Support | Customer support, on demand',
      cardType: 'link',
      cardTypeId: 1,
      image: 'https://picsum.photos/1057/564',
      imageWidth: 1057,
      imageHeight: 564,
      createdAt: '2020-11-28T00:01:29+00:00',
      url: 'http://Loopsupport.com',
      totalFavorites: 0,
      description:
        'We\u2019ll take care of customer support for you & faster responses, smaller backlogs, and happier customers. We help growing companies provide great customer support.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:01:39+00:00',
    },
    {
      id: 12,
      token: 'cd051e69a5b206c8588f4b114e7325d5ae93f154a2815026',
      userId: 7,
      title: 'Blastable',
      cardType: 'link',
      cardTypeId: 1,
      image: null,
      imageWidth: null,
      imageHeight: null,
      createdAt: '2020-11-28T00:01:22+00:00',
      url: 'http://blastable.io',
      totalFavorites: 0,
      description: 'Blastable handles email support tickets for you.',
      user: {
        id: 7,
        firstName: null,
        lastName: null,
        email: 'brian@trytrig.com',
      },
      cardFavorite: null,
      isFavorited: false,
      lastAttemptedSync: '2020-11-28T00:01:31+00:00',
    },
  ],
  meta: { page: 0, totalPages: 1, totalResults: 19 },
};
